
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mark
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nestdb
    ports:
      - "5499:5432"

volumes:
  db_data:
